### ISSUE TITLE
Continue support for Chromebooks/ChromeOS in Peerio 2

### ISSUE THREAD

**Issue by ryderdavid** [PeerioTechnologies/peerio#1]
Hi, I have actually reached out to your FB messenger page, but figured it would be best to add this here. 

I'm pretty concerned about the dropping of Chromebooks from support in Peerio going forward. I can understand the rationale, that given Google's dropping of support of Chrome* apps on traditional desktops, the market base has likely shrunk. That said, Google continues to support Chrome*books* as a fertile environment for apps, and leaving out this platform from the updated Peerio really guts certain workflows and some of the most important use cases. 

The specific one I can think of is the following: 
I use Peerio with partners who also use Chromebooks as the two are mutually reinforcing on delivering for a specific user profile - in a surveillance-hostile environment, with low tech skills, when the increased endpoint security on ChromeOS provides dramatically increased peace of mind. Going out and getting a regular PC opens new attack surfaces, and new opportunities for security breakdowns due to bad user actions, where ChromeOS + Peerio has provided a "good enough" secure workflow for users who aren't going to figure out how to use PGP or run Linux on the Chromebook, etc. Just quitting Peerio would be difficult, as there aren't other apps filling this particular niche of security + UX. 

I really hope you reconsider, as this is an admittedly smaller, but vital demographic being left out in ending ChromeOS support.

**Comment by flohdot** [comment]
Hi @ryderdavid, you're definitely in the right place! :) We were quite sad to see Chrome apps dropped from traditional desktops. We originally developed Peerio 1 Chrome-first and added support for nwjs apps on top of that.

That said, at this point the Chrome app just isn't being used very much due to the limited OS support. Additionally, our new architecture is based on the more-powerful and more widely supported Electron rather than nwjs, and it's not so easy to port all the new code towards a ChromeOS app anymore. We're not planning ChromeOS support anytime soon. 

That said, if we continue to hear that support is needed by a large user base, we'll happily reconsider and reopen the issue. In the meantime, we're also giving plenty of serious thought to more portable workflows as well as more secure OS contexts, which we of course know are important to a lot of users.
